BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

printf "\n"
printf "   ${BLUE}========================================================\n"
printf "   ${BLUE}|${NC}${GREEN}                  Useful Commands                     ${BLUE}|\n"
printf "   ${BLUE}========================================================\n"
printf "   ${BLUE}|${GREEN} update  ${BLUE}| ${YELLOW}updates the system                         ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} install ${BLUE}| ${YELLOW}installs package(s)                        ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} remove  ${BLUE}| ${YELLOW}removes package(s)                         ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} disk    ${BLUE}| ${YELLOW}shows disk usage                           ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} bashtop ${BLUE}| ${YELLOW}process manager                            ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} rm      ${BLUE}| ${YELLOW}removes file(s) with confirmation prompt   ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} compact ${BLUE}| ${YELLOW}compresses file(s) into a tar archive      ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} untar   ${BLUE}| ${YELLOW}extracts tar archive                       ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} cat     ${BLUE}| ${YELLOW}displays file content                      ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} ls      ${BLUE}| ${YELLOW}displays file and directory information    ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} find    ${BLUE}| ${YELLOW}searches for files or directories          ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} docker  ${BLUE}| ${YELLOW}executes Docker commands with sudo         ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} top     ${BLUE}| ${YELLOW}displays system processes and resource     ${BLUE}|\n"
printf "   ${BLUE}========================================================\n"
printf "   ${BLUE}|${GREEN}                    Networking                        ${BLUE}|\n"
printf "   ${BLUE}========================================================\n"
printf "   ${BLUE}|${GREEN} ports       ${BLUE}| ${YELLOW}displays open ports                    ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} ips         ${BLUE}| ${YELLOW}displays IP addresses                  ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} dns         ${BLUE}| ${YELLOW}performs DNS lookup                    ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} traceroute  ${BLUE}| ${YELLOW}performs traceroute                    ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} iftop       ${BLUE}| ${YELLOW}displays bandwidth usage by connection ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} iperfudp    ${BLUE}| ${YELLOW}performs UDP network test              ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} iperfserv   ${BLUE}| ${YELLOW}runs iPerf server                      ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} iperfclient ${BLUE}| ${YELLOW}performs iPerf network test            ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} iperfmult   ${BLUE}| ${YELLOW}performs iPerf multicast network test  ${BLUE}|\n"
printf "   ${BLUE}========================================================\n"
printf "   ${BLUE}|${GREEN}                     Misc                             ${BLUE}|\n"
printf "   ${BLUE}========================================================\n"
printf "   ${BLUE}|${GREEN} please  ${BLUE}| ${YELLOW}executes command with sudo privileges      ${BLUE}|\n"
printf "   ${BLUE}|${GREEN} linux   ${BLUE}| ${YELLOW}displays system information                ${BLUE}|\n"
printf "   ${BLUE}========================================================\n"
printf "   ${BLUE}|${GREEN}                 By. kaio Guilherme                   ${BLUE}|\n"
printf "   ${BLUE}========================================================\n"${NC}